class AddIndexToTables < ActiveRecord::Migration
  def change
    add_index :instruments, :project_id unless index_exists?(:instruments, :project_id)
    add_index :instruments, :updated_at unless index_exists?(:instruments, :updated_at)
    add_index :instruments, :deleted_at unless index_exists?(:instruments, :deleted_at)
    add_index :instrument_translations, :instrument_id unless index_exists?(:instrument_translations, :instrument_id)
    add_index :sections, :updated_at unless index_exists?(:sections, :updated_at)
    add_index :sections, :deleted_at unless index_exists?(:sections, :deleted_at)
    add_index :instructions, :updated_at unless index_exists?(:instructions, :updated_at)
    add_index :questions, :updated_at unless index_exists?(:questions, :updated_at)
    add_index :questions, :deleted_at unless index_exists?(:questions, :deleted_at)
    add_index :question_translations, :question_id unless index_exists?(:question_translations, :question_id)
    add_index :instrument_questions, :updated_at unless index_exists?(:instrument_questions, :updated_at)
    add_index :api_keys, :access_token unless index_exists?(:api_keys, :access_token)
    add_index :condition_skips, :instrument_question_id unless index_exists?(:condition_skips, :instrument_question_id)
    add_index :condition_skips, :updated_at unless index_exists?(:condition_skips, :updated_at)
    add_index :condition_skips, :deleted_at unless index_exists?(:condition_skips, :deleted_at)
    add_index :critical_responses, :updated_at unless index_exists?(:critical_responses, :updated_at)
    add_index :critical_responses, :deleted_at unless index_exists?(:critical_responses, :deleted_at)
    add_index :display_instructions, :deleted_at unless index_exists?(:display_instructions, :deleted_at)
    add_index :display_instructions, :updated_at unless index_exists?(:display_instructions, :updated_at)
    add_index :display_instructions, :display_id unless index_exists?(:display_instructions, :display_id)
    add_index :display_instructions, :instruction_id unless index_exists?(:display_instructions, :instruction_id)
    add_index :display_instructions, :instrument_question_id unless index_exists?(:display_instructions, :instrument_question_id)
    add_index :display_translations, :display_id unless index_exists?(:display_translations, :display_id)
    add_index :displays, :updated_at unless index_exists?(:displays, :updated_at)
    add_index :follow_up_questions, :updated_at unless index_exists?(:follow_up_questions, :updated_at)
    add_index :follow_up_questions, :instrument_question_id unless index_exists?(:follow_up_questions, :instrument_question_id)
    add_index :follow_up_questions, :deleted_at unless index_exists?(:follow_up_questions, :deleted_at)
    add_index :loop_questions, :updated_at unless index_exists?(:loop_questions, :updated_at)
    add_index :loop_questions, :deleted_at unless index_exists?(:loop_questions, :deleted_at)
    add_index :multiple_skips, :updated_at unless index_exists?(:multiple_skips, :updated_at)
    add_index :multiple_skips, :deleted_at unless index_exists?(:multiple_skips, :deleted_at)
    add_index :next_questions, :updated_at unless index_exists?(:next_questions, :updated_at)
    add_index :next_questions, :deleted_at unless index_exists?(:next_questions, :deleted_at)
    add_index :option_in_option_sets, :updated_at unless index_exists?(:option_in_option_sets, :updated_at)
    add_index :option_in_option_sets, :deleted_at unless index_exists?(:option_in_option_sets, :deleted_at)
    add_index :option_sets, :updated_at unless index_exists?(:option_sets, :updated_at)
    add_index :option_sets, :deleted_at unless index_exists?(:option_sets, :deleted_at)
    add_index :options, :updated_at unless index_exists?(:options, :updated_at)
    add_index :options, :deleted_at unless index_exists?(:options, :deleted_at)
    add_index :options, :identifier unless index_exists?(:options, :identifier)
  end
end
